@extends('layouts.negocio')
@section('titulo', 'Productos — Delivery Patacamaya')
@section('contenido-negocio')
<div class="page-heading d-sm-flex justify-content-between align-items-center"><div><h1 class="h2">Productos</h1><p class="text-secondary">Administra el catálogo de {{ $negocio->nombre }}.</p></div><a class="btn btn-primary touch-button" href="{{ route('negocio.productos.create', $negocio) }}"><i class="bi bi-plus-lg"></i> Nuevo producto</a></div>
<form class="card soft-card p-3 mb-4" method="GET"><div class="row g-2"><div class="col-12 col-lg-4"><label class="visually-hidden" for="buscar">Buscar</label><input class="form-control" id="buscar" name="buscar" value="{{ $filtros['buscar'] ?? '' }}" placeholder="Buscar por nombre"></div><div class="col-6 col-lg-3"><select class="form-select" name="categoria" aria-label="Filtrar categoría"><option value="">Todas las categorías</option>@foreach($categorias as $categoria)<option value="{{ $categoria->id }}" @selected((string)($filtros['categoria'] ?? '') === (string)$categoria->id)>{{ $categoria->nombre }}</option>@endforeach</select></div><div class="col-6 col-lg-2"><select class="form-select" name="activo" aria-label="Filtrar estado"><option value="">Cualquier estado</option><option value="1" @selected(($filtros['activo'] ?? '') === '1')>Activos</option><option value="0" @selected(($filtros['activo'] ?? '') === '0')>Inactivos</option></select></div><div class="col-8 col-lg-2"><select class="form-select" name="disponible" aria-label="Filtrar disponibilidad"><option value="">Toda disponibilidad</option><option value="1" @selected(($filtros['disponible'] ?? '') === '1')>Disponibles</option><option value="0" @selected(($filtros['disponible'] ?? '') === '0')>Agotados</option></select></div><div class="col-4 col-lg-1 d-grid"><button class="btn btn-outline-primary" aria-label="Aplicar filtros"><i class="bi bi-search"></i></button></div></div></form>
@if($productos->isEmpty())<div class="empty-state"><i class="bi bi-bag fs-1"></i><h2 class="h5 mt-3">No se encontraron productos</h2><p>Añade uno nuevo o cambia los filtros aplicados.</p></div>@else
<div class="card soft-card overflow-hidden d-none d-lg-block"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Producto</th><th>Categoría</th><th>Precio</th><th>Estado</th><th>Disponibilidad</th><th class="text-end">Acciones</th></tr></thead><tbody>@foreach($productos as $producto)<tr><td><div class="d-flex align-items-center gap-3">@if($producto->imagen)<img class="product-thumb" src="{{ Storage::url($producto->imagen) }}" alt="">@else<div class="product-thumb product-placeholder"><i class="bi bi-image"></i></div>@endif<strong>{{ $producto->nombre }}</strong></div></td><td>{{ $producto->categoria?->nombre ?? 'Sin categoría' }}</td><td>Bs {{ number_format((float)$producto->precio, 2, ',', '.') }}</td><td><span class="badge {{ $producto->activo ? 'text-bg-success' : 'text-bg-secondary' }}">{{ $producto->activo ? 'Activo' : 'Inactivo' }}</span></td><td><span class="badge {{ $producto->disponible ? 'text-bg-primary' : 'text-bg-warning' }}">{{ $producto->disponible ? 'Disponible' : 'Agotado' }}</span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary touch-target" href="{{ route('negocio.productos.edit', [$negocio, $producto]) }}">Editar</a></td></tr>@endforeach</tbody></table></div></div>
<div class="row g-3 d-lg-none">@foreach($productos as $producto)<div class="col-12 col-md-6"><article class="card soft-card catalog-card h-100">@if($producto->imagen)<img class="card-img-top catalog-image" src="{{ Storage::url($producto->imagen) }}" alt="Imagen de {{ $producto->nombre }}">@else<div class="catalog-image product-placeholder"><i class="bi bi-image fs-2"></i></div>@endif<div class="card-body"><div class="d-flex justify-content-between gap-2"><h2 class="h5">{{ $producto->nombre }}</h2><strong class="text-primary text-nowrap">Bs {{ number_format((float)$producto->precio, 2, ',', '.') }}</strong></div><p class="small text-secondary">{{ $producto->categoria?->nombre ?? 'Sin categoría' }}</p><div class="d-flex flex-wrap gap-2 mb-3"><span class="badge {{ $producto->activo ? 'text-bg-success' : 'text-bg-secondary' }}">{{ $producto->activo ? 'Activo' : 'Inactivo' }}</span><span class="badge {{ $producto->disponible ? 'text-bg-primary' : 'text-bg-warning' }}">{{ $producto->disponible ? 'Disponible' : 'Agotado' }}</span></div><a class="btn btn-outline-primary touch-button w-100" href="{{ route('negocio.productos.edit', [$negocio, $producto]) }}">Editar producto</a><div class="grid-buttons mt-2"><form method="POST" action="{{ route('negocio.productos.estado', [$negocio, $producto]) }}">@csrf @method('PATCH')<button class="btn btn-outline-secondary touch-button w-100">{{ $producto->activo ? 'Desactivar' : 'Activar' }}</button></form><form method="POST" action="{{ route('negocio.productos.disponibilidad', [$negocio, $producto]) }}">@csrf @method('PATCH')<button class="btn btn-outline-secondary touch-button w-100">{{ $producto->disponible ? 'Agotar' : 'Disponible' }}</button></form></div></div></article></div>@endforeach</div>
<div class="mt-4">{{ $productos->links() }}</div>@endif
@endsection
