@extends('layouts.app')
@section('contenido')
@php($actual = $negocio ?? auth()->user()->negocios()->find(session('negocio_actual_id')) ?? auth()->user()->negocios()->first())
<div class="admin-layout">
<aside class="admin-sidebar card soft-card d-none d-lg-block"><div class="card-body p-3"><div class="small text-uppercase fw-bold text-secondary mb-2">Mi negocio</div><nav class="nav nav-pills flex-column gap-1"><a class="nav-link {{ request()->routeIs('negocio.inicio') ? 'active' : '' }}" href="{{ route('negocio.inicio') }}"><i class="bi bi-house me-2"></i>Inicio</a>@if($actual)<a class="nav-link {{ request()->routeIs('negocio.mi-negocio.*') ? 'active' : '' }}" href="{{ route('negocio.mi-negocio.edit', $actual) }}"><i class="bi bi-shop me-2"></i>Mi negocio</a><a class="nav-link {{ request()->routeIs('negocio.horarios.*') ? 'active' : '' }}" href="{{ route('negocio.horarios.edit', $actual) }}"><i class="bi bi-clock me-2"></i>Horarios</a><a class="nav-link {{ request()->routeIs('negocio.categorias-producto.*') ? 'active' : '' }}" href="{{ route('negocio.categorias-producto.index', $actual) }}"><i class="bi bi-grid me-2"></i>Categorías de productos</a><a class="nav-link {{ request()->routeIs('negocio.productos.*') ? 'active' : '' }}" href="{{ route('negocio.productos.index', $actual) }}"><i class="bi bi-box-seam me-2"></i>Productos</a><a class="nav-link {{ request()->routeIs('negocio.pedidos.*') ? 'active' : '' }}" href="{{ route('negocio.pedidos.index', $actual) }}"><i class="bi bi-receipt me-2"></i>Pedidos</a>@endif</nav><hr><div class="small text-secondary mb-2"><i class="bi bi-person-circle me-2"></i>{{ auth()->user()->nombres }}</div><form method="POST" action="{{ route('logout') }}">@csrf<button class="btn btn-sm btn-outline-danger w-100"><i class="bi bi-box-arrow-right me-1"></i>Cerrar sesión</button></form></div></aside>
<div class="admin-content">@if($actual && $actual->estado !== 'aprobado')<div class="alert alert-warning"><i class="bi bi-exclamation-triangle me-2"></i>Tu negocio todavía no está aprobado para mostrarse a clientes.</div>@endif @if($actual && ! $actual->activo)<div class="alert alert-danger">Este negocio está desactivado y no será visible para clientes.</div>@endif @yield('contenido-negocio')</div>
</div>
<nav class="mobile-bottom-nav d-lg-none"><a class="mobile-nav-item {{ request()->routeIs('negocio.inicio') ? 'active' : '' }}" href="{{ route('negocio.inicio') }}"><i class="bi bi-house"></i><span>Inicio</span></a>@if($actual)<a class="mobile-nav-item {{ request()->routeIs('negocio.productos.*') ? 'active' : '' }}" href="{{ route('negocio.productos.index', $actual) }}"><i class="bi bi-box-seam"></i><span>Productos</span></a><a class="mobile-nav-item {{ request()->routeIs('negocio.pedidos.*') ? 'active' : '' }}" href="{{ route('negocio.pedidos.index', $actual) }}"><i class="bi bi-receipt"></i><span>Pedidos</span></a><a class="mobile-nav-item {{ request()->routeIs('negocio.categorias-producto.*') ? 'active' : '' }}" href="{{ route('negocio.categorias-producto.index', $actual) }}"><i class="bi bi-grid"></i><span>Catálogo</span></a>@endif<button class="mobile-nav-item" data-bs-toggle="offcanvas" data-bs-target="#menuNegocio"><i class="bi bi-grid-3x3-gap"></i><span>Más</span></button></nav>
<div class="offcanvas offcanvas-bottom mobile-more-menu" id="menuNegocio" tabindex="-1"><div class="offcanvas-header"><h2 class="h5">Más opciones</h2><button class="btn-close" data-bs-dismiss="offcanvas" aria-label="Cerrar"></button></div><div class="offcanvas-body">@if($actual)<a class="more-menu-link" href="{{ route('negocio.mi-negocio.edit', $actual) }}"><i class="bi bi-shop"></i><strong>Mi negocio</strong></a><a class="more-menu-link" href="{{ route('negocio.horarios.edit', $actual) }}"><i class="bi bi-clock"></i><strong>Horarios</strong></a>@endif<div class="more-menu-link"><i class="bi bi-person-circle"></i><strong>{{ auth()->user()->nombres }}</strong></div><form method="POST" action="{{ route('logout') }}">@csrf<button class="more-menu-link text-danger border-0 bg-transparent w-100"><i class="bi bi-box-arrow-right"></i><strong>Cerrar sesión</strong></button></form></div></div>
@endsection
