@csrf
@isset($subcategoria) @method('PUT') @endisset
<div class="row g-3">
    <div class="col-12"><label class="form-label" for="categoria_negocio_id">Categoría general</label><select class="form-select @error('categoria_negocio_id') is-invalid @enderror" id="categoria_negocio_id" name="categoria_negocio_id" required><option value="">Seleccionar categoría</option>@foreach($categorias as $categoria)<option value="{{ $categoria->id }}" @selected(old('categoria_negocio_id', $subcategoria->categoria_negocio_id ?? '') == $categoria->id)>{{ $categoria->nombre }}</option>@endforeach</select>@error('categoria_negocio_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label" for="nombre">Nombre</label><input class="form-control @error('nombre') is-invalid @enderror" id="nombre" name="nombre" value="{{ old('nombre', $subcategoria->nombre ?? '') }}" maxlength="100" required>@error('nombre')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label" for="descripcion">Descripción</label><textarea class="form-control" id="descripcion" name="descripcion" rows="3" maxlength="255">{{ old('descripcion', $subcategoria->descripcion ?? '') }}</textarea></div>
    <div class="col-12"><label class="form-label" for="icono">Bootstrap Icon</label><input class="form-control @error('icono') is-invalid @enderror" id="icono" name="icono" value="{{ old('icono', $subcategoria->icono ?? '') }}" placeholder="bi-shop" maxlength="100">@error('icono')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><div class="form-check form-switch"><input type="hidden" name="activo" value="0"><input class="form-check-input" id="activo" name="activo" type="checkbox" value="1" @checked(old('activo', $subcategoria->activo ?? true))><label class="form-check-label" for="activo">Subcategoría activa</label></div></div>
</div>
<div class="d-grid d-sm-flex justify-content-sm-end gap-2 mt-4"><a class="btn btn-light order-2 order-sm-1" href="{{ route('administrador.subcategorias.index') }}">Cancelar</a><button class="btn btn-primary order-1 order-sm-2" type="submit"><i class="bi bi-check-lg me-1"></i>Guardar</button></div>
