@extends('layouts.admin')
@section('titulo', 'Subcategorías — Delivery Patacamaya')
@section('contenido-admin')
<div class="page-heading d-sm-flex justify-content-between align-items-center"><div><h1 class="h2">Subcategorías</h1><p class="text-secondary">Clasificaciones específicas para cada tipo de negocio.</p></div><a class="btn btn-primary touch-button" href="{{ route('administrador.subcategorias.create') }}"><i class="bi bi-plus-lg me-1"></i>Nueva subcategoría</a></div>
<form class="card soft-card p-3 mb-3" method="GET"><div class="row g-2"><div class="col-12 col-md"><input class="form-control" name="buscar" value="{{ $filtros['buscar'] ?? '' }}" placeholder="Buscar por nombre"></div><div class="col-12 col-sm"><select class="form-select" name="categoria"><option value="">Todas las categorías</option>@foreach($categorias as $categoria)<option value="{{ $categoria->id }}" @selected(($filtros['categoria'] ?? '') == $categoria->id)>{{ $categoria->nombre }}</option>@endforeach</select></div><div class="col-8 col-sm"><select class="form-select" name="activo"><option value="">Todo estado</option><option value="1" @selected(($filtros['activo'] ?? '') === '1')>Activas</option><option value="0" @selected(($filtros['activo'] ?? '') === '0')>Inactivas</option></select></div><div class="col-4 col-md-auto d-grid"><button class="btn btn-outline-success"><i class="bi bi-funnel"></i></button></div></div></form>
<div class="d-none d-md-block card soft-card overflow-hidden"><div class="table-responsive"><table class="table table-hover mb-0"><thead class="table-light"><tr><th>Subcategoría</th><th>Categoría</th><th>Descripción</th><th>Estado</th><th class="text-end">Acciones</th></tr></thead><tbody>@forelse($subcategorias as $subcategoria)<tr><td class="fw-semibold">{{ $subcategoria->nombre }}</td><td>{{ $subcategoria->categoria->nombre }}</td><td>{{ $subcategoria->descripcion ?: '—' }}</td><td><span class="badge {{ $subcategoria->activo ? 'text-bg-success' : 'text-bg-secondary' }}">{{ $subcategoria->activo ? 'Activa' : 'Inactiva' }}</span></td><td class="text-end">@include('admin.subcategorias._acciones')</td></tr>@empty<tr><td colspan="5" class="text-center py-5">No se encontraron subcategorías.</td></tr>@endforelse</tbody></table></div></div>
<div class="d-md-none d-grid gap-3">@forelse($subcategorias as $subcategoria)<article class="card soft-card p-3"><div class="d-flex justify-content-between gap-2"><div><h2 class="h5 mb-1">{{ $subcategoria->nombre }}</h2><div class="text-secondary small"><i class="bi bi-tag me-1"></i>{{ $subcategoria->categoria->nombre }}</div></div><span class="badge align-self-start {{ $subcategoria->activo ? 'text-bg-success' : 'text-bg-secondary' }}">{{ $subcategoria->activo ? 'Activa' : 'Inactiva' }}</span></div><p class="small text-secondary my-3">{{ $subcategoria->descripcion ?: 'Sin descripción' }}</p><div class="d-flex justify-content-end">@include('admin.subcategorias._acciones')</div></article>@empty<div class="empty-state">No se encontraron subcategorías.</div>@endforelse</div>
<div class="mt-3">{{ $subcategorias->links() }}</div>
@endsection
