@extends('layouts.cliente')
@section('titulo','Checkout — Delivery Patacamaya')
@section('contenido-cliente')
<a class="btn btn-link px-0" href="{{ route('cliente.carrito.index') }}"><i class="bi bi-arrow-left"></i> Volver al carrito</a><h1 class="h2">Confirmar pedido</h1>
@if(!$hayZonas)<div class="empty-state my-3"><i class="bi bi-geo-alt fs-1"></i><h2 class="h5 mt-2">No existen zonas de entrega disponibles actualmente.</h2><p>Administración todavía no configuró zonas activas.</p></div>
@elseif($direcciones->isEmpty())<div class="empty-state my-3"><h2 class="h5">Necesitas registrar una dirección antes de realizar el pedido.</h2><a class="btn btn-primary" href="{{ route('cliente.direcciones.create') }}">Agregar dirección</a></div>
@else
<form method="POST" action="{{ route('cliente.checkout.store') }}">@csrf
<div class="row g-3"><div class="col-lg-7"><section class="card soft-card p-3 mb-3"><h2 class="h5">{{ $carrito->negocio->nombre }}</h2>@foreach($carrito->items as $item)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $item->cantidad }} × {{ $item->producto->nombre }}</span><span>Bs {{ number_format((float)$item->producto->precio*$item->cantidad,2,',','.') }}</span></div>@endforeach</section>
<section class="card soft-card p-3 mb-3"><h2 class="h5">Dirección de entrega</h2>@foreach($direcciones as $direccion)<label class="selection-card p-3 rounded border mb-2 d-block"><input type="radio" name="direccion_id" value="{{ $direccion->id }}" @checked(old('direccion_id',$direcciones->firstWhere('predeterminada',true)?->id ?? $direcciones->first()->id)===$direccion->id)> <strong>{{ $direccion->nombre }}</strong><small class="d-block ms-4">{{ $direccion->zona->nombre }} · {{ $direccion->direccion_referencia }}</small></label>@endforeach @error('direccion_id')<div class="text-danger">{{ $message }}</div>@enderror</section>
<section class="card soft-card p-3"><h2 class="h5">Pago y observaciones</h2><div class="d-flex gap-4 mb-3"><label><input type="radio" name="metodo_pago" value="efectivo" @checked(old('metodo_pago','efectivo')==='efectivo')> Efectivo</label><label><input type="radio" name="metodo_pago" value="qr" @checked(old('metodo_pago')==='qr')> QR</label></div><label class="form-label" for="observaciones">Observaciones (opcional)</label><textarea class="form-control" id="observaciones" name="observaciones" maxlength="500" placeholder="Sin cebolla, por favor.">{{ old('observaciones') }}</textarea></section></div>
@php($subtotal=$carrito->items->sum(fn($i)=>(float)$i->producto->precio*$i->cantidad))<aside class="col-lg-5"><div class="card soft-card p-3 checkout-summary"><h2 class="h5">Resumen</h2><div class="d-flex justify-content-between"><span>Subtotal</span><strong>Bs {{ number_format($subtotal,2,',','.') }}</strong></div><div class="d-flex justify-content-between"><span>Entrega</span><strong>Bs 0,00</strong></div><hr><div class="d-flex justify-content-between fs-5"><span>Total</span><strong>Bs {{ number_format($subtotal,2,',','.') }}</strong></div><button class="btn btn-primary btn-lg mt-3">Confirmar pedido</button></div></aside></div></form>
@endif
@endsection