@extends('layouts.negocio')
@section('titulo', 'Categorías de productos — Delivery Patacamaya')
@section('contenido-negocio')
<div class="page-heading d-sm-flex justify-content-between align-items-center"><div><h1 class="h2">Categorías de productos</h1><p class="text-secondary">Organiza el catálogo de {{ $negocio->nombre }}.</p></div><a class="btn btn-primary touch-button" href="{{ route('negocio.categorias-producto.create', $negocio) }}"><i class="bi bi-plus-lg"></i> Nueva categoría</a></div>
@if($categorias->isEmpty())
<div class="empty-state"><i class="bi bi-tags fs-1"></i><h2 class="h5 mt-3">Todavía no hay categorías</h2><p>Crea la primera para comenzar a organizar tus productos.</p></div>
@else
<div class="card soft-card overflow-hidden d-none d-md-block"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Nombre</th><th>Productos</th><th>Orden</th><th>Estado</th><th class="text-end">Acciones</th></tr></thead><tbody>@foreach($categorias as $categoria)<tr><td><strong>{{ $categoria->nombre }}</strong><div class="small text-secondary">{{ $categoria->descripcion }}</div></td><td>{{ $categoria->productos_count }}</td><td>{{ $categoria->orden ?? '—' }}</td><td><span class="badge {{ $categoria->activo ? 'text-bg-success' : 'text-bg-secondary' }}">{{ $categoria->activo ? 'Activa' : 'Inactiva' }}</span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary touch-target" href="{{ route('negocio.categorias-producto.edit', [$negocio, $categoria]) }}">Editar</a><form class="d-inline" method="POST" action="{{ route('negocio.categorias-producto.estado', [$negocio, $categoria]) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-secondary touch-target">{{ $categoria->activo ? 'Desactivar' : 'Activar' }}</button></form></td></tr>@endforeach</tbody></table></div></div>
<div class="d-grid gap-3 d-md-none">@foreach($categorias as $categoria)<article class="card soft-card p-3"><div class="d-flex justify-content-between gap-2"><div><h2 class="h5 mb-1">{{ $categoria->nombre }}</h2><span class="small text-secondary">{{ $categoria->productos_count }} productos</span></div><span class="badge align-self-start {{ $categoria->activo ? 'text-bg-success' : 'text-bg-secondary' }}">{{ $categoria->activo ? 'Activa' : 'Inactiva' }}</span></div><p class="small text-secondary my-3">{{ $categoria->descripcion ?: 'Sin descripción.' }}</p><div class="d-grid grid-buttons"><a class="btn btn-outline-primary touch-button" href="{{ route('negocio.categorias-producto.edit', [$negocio, $categoria]) }}">Editar</a><form method="POST" action="{{ route('negocio.categorias-producto.estado', [$negocio, $categoria]) }}">@csrf @method('PATCH')<button class="btn btn-outline-secondary touch-button w-100">{{ $categoria->activo ? 'Desactivar' : 'Activar' }}</button></form></div></article>@endforeach</div>
@endif
@endsection
